/*
 *    Copyright 2025-2026 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package pro.chenggang.project.reactive.ai.lite.core.tool;

import lombok.AccessLevel;
import lombok.Builder;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import lombok.extern.jackson.Jacksonized;

/**
 * Default immutable implementation of {@link ToolDefinition}, serving as a value object for
 * metadata describing a tool exposed to an AI model.
 * <p>
 * This class captures the core attributes required for tool registration and invocation:
 * <ul>
 *   <li><strong>name</strong> – a unique identifier used to reference the tool in requests and responses.</li>
 *   <li><strong>description</strong> – a natural language explanation that guides the AI model when to select this tool.</li>
 *   <li><strong>inputSchema</strong> – a JSON Schema defining the expected structure of parameters, enabling the
 *         AI to produce valid inputs. When no schema is provided, an empty JSON object is used as default,
 *         indicating the tool expects no arguments.</li>
 *   <li><strong>strict</strong> – a flag that, when set to {@code true}, requests the model provider to strictly
 *         enforce the schema against generated arguments. If {@code false}, enforcement is relaxed. A {@code null}
 *         value delegates the choice to the provider’s default behavior.</li>
 * </ul>
 * <p>
 * Instances are created exclusively through the static builder provided by Lombok’s {@code @Builder}. This design
 * ensures immutability and thread safety, making the definition suitable for sharing across concurrent tool execution
 * contexts. The {@code @Jacksonized} annotation guarantees proper JSON serialization/deserialization with the
 * immutable pattern, supporting configuration files, network transport, and persistence without extra effort.
 * <p>
 * The private constructor generated by {@code @RequiredArgsConstructor} enforces non-null constraints on mandatory
 * fields, catching misconfiguration early at build time rather than at runtime.
 *
 * @author Gang Cheng
 * @version 0.1.0
 * @see ToolDefinition
 */
@Jacksonized
@Builder
@RequiredArgsConstructor(access = AccessLevel.PRIVATE)
public class DefaultToolDefinition implements ToolDefinition {

    /**
     * The unique identifier for the tool.
     * <p>
     * This name must be stable, non-null, and unique within a tool registry. It is used as the key when the AI
     * model selects a tool to invoke and when the corresponding result is matched back to the original request.
     * Choosing a name that reflects the tool's action (e.g., {@code "get_weather"}) improves readability and
     * reduces ambiguity in prompt engineering.
     */
    @NonNull
    private final String name;

    /**
     * A human-readable description explaining the tool’s purpose, capabilities, and appropriate usage scenarios.
     * <p>
     * This description is passed to the AI model as part of the tool specification. A well-crafted description
     * includes details about when the tool should be used and what information it requires, directly influencing
     * the model’s decision to call this tool. The content should be clear, concise, and avoid technical jargon
     * that the model might misinterpret.
     */
    @NonNull
    private final String description;

    /**
     * A JSON Schema (string representation) that describes the expected shape of the tool’s input parameters.
     * <p>
     * If the tool accepts parameters, this schema defines the required structure, data types, and constraints.
     * A {@code null} value stored here is treated as equivalent to the empty schema {@code "{}"}, indicating
     * no parameters are needed. This default simplifies tool definitions when inputs are not applicable.
     * <p>
     * The schema should follow the standard JSON Schema specification (Draft‑2020‑12 or earlier) to ensure
     * broad compatibility with model providers.
     */
    private final String inputSchema;

    /**
     * Controls whether the AI model must strictly adhere to the provided {@link #inputSchema} when generating
     * arguments.
     * <p>
     * When set to {@code true}, the provider is instructed to reject any generated arguments that do not conform
     * exactly to the schema. This is useful for tools that rely on precise input validation. A value of
     * {@code false} allows the provider to be lenient, which may improve usability with models that occasionally
     * produce near‑valid JSON. If left {@code null} (the default), the behavior is determined by the model
     * provider’s internal settings, offering a balanced out‑of‑the‑box experience.
     */
    private final Boolean strict;

    /**
     * Returns the unique name of the tool.
     *
     * @return the tool’s name, as defined at construction time; never {@code null}
     * @see #name
     */
    @Override
    public String name() {
        return this.name;
    }

    /**
     * Returns the description that guides the AI model on tool usage.
     *
     * @return the description string; never {@code null}
     * @see #description
     */
    @Override
    public String description() {
        return this.description;
    }

    /**
     * Returns the JSON schema for the tool’s input parameters.
     * <p>
     * If the tool was constructed without a schema (field is {@code null}), this method returns {@code "{}"}
     * to represent the absence of required parameters. This unconditional default allows callers to safely
     * assume a non‑null return value and avoids null‑checks in downstream logic.
     *
     * @return a JSON schema string, never {@code null}; defaults to {@code "{}"} if no schema was provided
     * @see #inputSchema
     */
    @Override
    public String inputSchema() {
        return this.inputSchema == null ? "{}" : this.inputSchema;
    }

    /**
     * Indicates whether strict schema adherence is requested.
     *
     * @return {@code true} to enforce strict validation, {@code false} to relax it, or {@code null} to use
     *         the provider’s default behavior
     * @see #strict
     */
    @Override
    public Boolean strict() {
        return this.strict;
    }

}