/*
 *    Copyright 2025-2026 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package pro.chenggang.project.reactive.ai.lite.core.option;

/**
 * Represents the different types of data that can be part of an AI model's response.
 * This enum is used to categorize and identify the various components within a response,
 * especially in a streaming context where data arrives in chunks.
 *
 * @author Cheng Gang
 * @version 0.1.0
 */
public enum ResponseDataType {

    /**
     * Indicates an unknown or uncategorized type of response data.
     */
    UNKNOWN,

    /**
     * Represents the role of the message author (e.g., 'user', 'assistant').
     */
    ROLE,

    /**
     * Represents the original message content sent in the request.
     */
    REQUEST_MESSAGE,

    /**
     * Represents the reasoning or thought process of the AI model before providing the final answer.
     */
    REASONING_CONTENT,

    /**
     * Represents the main answer or content generated by the AI model.
     */
    ANSWER_CONTENT,

    /**
     * Represents a request from the model to call a specific tool or function.
     */
    TOOL_CALL,

    /**
     * Represents metadata about the model's usage for the request, such as token counts.
     */
    USAGE,

    /**
     * Indicates that the response stream has finished.
     */
    FINISHED,

    ;
}
