/*
 *    Copyright 2025-2026 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package pro.chenggang.project.reactive.ai.lite.core.option;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Defines the role of the entity that authored a message in a conversation.
 * <p>
 * In chat-based LLM interactions, messages are typically attributed to specific roles,
 * such as the system providing instructions, the user asking questions, the assistant
 * (model) responding, or a tool returning results.
 * </p>
 *
 * @author Cheng Gang
 * @version 0.1.0
 */
public enum Role {

    /**
     * System message.
     * <p>
     * Used for providing instructions or context to guide the model's behavior.
     * </p>
     */
    @JsonProperty("system")
    SYSTEM,

    /**
     * User message.
     * <p>
     * Used for messages originating from the end-user interacting with the AI.
     * </p>
     */
    @JsonProperty("user")
    USER,

    /**
     * Assistant message.
     * <p>
     * Used for responses generated by the language model.
     * </p>
     */
    @JsonProperty("assistant")
    ASSISTANT,

    /**
     * Tool message.
     * <p>
     * Used for conveying the output or results of a tool call back to the model.
     * </p>
     */
    @JsonProperty("tool")
    TOOL,

    ;

    /**
     * Gets the lowercase string value of this role.
     * <p>
     * This method returns the role name in lowercase format, which is typically used
     * for serialization and API communication purposes with LLM providers.
     * </p>
     *
     * @return the lowercase string representation of this role (e.g., "system", "user", "assistant", "tool")
     */
    public String getValue() {
        return this.name().toLowerCase();
    }

}
