/*
 *    Copyright 2025-2026 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package pro.chenggang.project.reactive.ai.lite.core.option;

import lombok.AccessLevel;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import pro.chenggang.project.reactive.ai.lite.core.message.chunk.RawStreamDataChunk;
import pro.chenggang.project.reactive.ai.lite.core.message.chunk.StreamDataChunk;
import pro.chenggang.project.reactive.ai.lite.core.message.chunk.TextStreamDataChunk;
import pro.chenggang.project.reactive.ai.lite.core.message.chunk.ToolCallStreamDataChunk;
import pro.chenggang.project.reactive.ai.lite.core.message.chunk.UsageStreamDataChunk;

/**
 * Defines the types of response data chunks returned by AI models.
 * <p>
 * In a streaming response, the data is delivered in multiple fragments, each serving a
 * different purpose. This enumeration categorizes these fragments and links them to their
 * corresponding Java representation (implementations of {@link StreamDataChunk}).
 * </p>
 *
 * @author Gang Cheng
 * @version 0.1.0
 */
@Getter
@RequiredArgsConstructor(access = AccessLevel.PRIVATE)
public enum StreamDataType {

    /**
     * Represents raw, unclassified data, typically when the format is unexpected.
     * Tied to {@link RawStreamDataChunk}.
     */
    UNKNOWN(RawStreamDataChunk.class),

    /**
     * Represents the role associated with the upcoming message content (e.g., assistant).
     * Tied to {@link TextStreamDataChunk}.
     */
    ROLE(TextStreamDataChunk.class),

    /**
     * Represents the model's internal reasoning or thought process before generating the final answer.
     * Tied to {@link TextStreamDataChunk}.
     */
    REASONING_CONTENT(TextStreamDataChunk.class),

    /**
     * Represents the actual textual answer generated by the model.
     * Tied to {@link TextStreamDataChunk}.
     */
    ANSWER_CONTENT(TextStreamDataChunk.class),

    /**
     * Represents a request by the model to invoke a specific tool or function.
     * Tied to {@link ToolCallStreamDataChunk}.
     */
    TOOL_CALL(ToolCallStreamDataChunk.class),

    /**
     * Represents token usage metrics provided at the end of the response.
     * Tied to {@link UsageStreamDataChunk}.
     */
    USAGE(UsageStreamDataChunk.class),

    /**
     * Acts as a termination signal indicating the stream has completed normally.
     * Tied to {@link TextStreamDataChunk}.
     */
    FINISHED(TextStreamDataChunk.class),

    ;

    /**
     * The class type of the {@link StreamDataChunk} that carries this specific data type.
     */
    private final Class<? extends StreamDataChunk> dataChunkType;
}
