/*
 *    Copyright 2025-2026 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package pro.chenggang.project.reactive.ai.lite.core.option;

import lombok.AccessLevel;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import pro.chenggang.project.reactive.ai.lite.core.message.chunk.RawStreamDataChunk;
import pro.chenggang.project.reactive.ai.lite.core.message.chunk.StreamDataChunk;
import pro.chenggang.project.reactive.ai.lite.core.message.chunk.TextStreamDataChunk;
import pro.chenggang.project.reactive.ai.lite.core.message.chunk.ToolCallStreamDataChunk;
import pro.chenggang.project.reactive.ai.lite.core.message.chunk.UsageStreamDataChunk;

/**
 * Enumerates the semantic categories of streaming response data chunks emitted by AI models.
 * <p>
 * Large language models often deliver responses incrementally through a stream of events,
 * each representing a different facet of the generation process. This enumeration provides a
 * typed contract for those events, associating each logical category with a concrete
 * {@link StreamDataChunk} subclass that carries the domain‑specific payload.
 * </p>
 * <p>
 * By classifying stream fragments into these well‑known types, downstream processing code can
 * dispatch on the chunk type, apply appropriate transformations, and avoid fragile manual
 * string parsing. For instance, reasoning content may be displayed differently from the final
 * answer, tool‑call requests require special handling, and usage information is typically
 * aggregated for billing or monitoring purposes.
 * </p>
 * <p>
 * The constants are ordered in a way that reflects a typical lifecycle: an optional
 * reasoning phase, the assistant's role announcement, textual answer content, possible
 * tool‑call invocations, usage statistics, and finally a termination signal.
 * </p>
 *
 * @author Gang Cheng
 * @version 0.1.0
 */
@Getter
@RequiredArgsConstructor(access = AccessLevel.PRIVATE)
public enum StreamDataType {

    /**
     * Catch‑all category for data that does not match any expected format.
     * <p>
     * When the stream produces a fragment whose structure is unrecognized—perhaps due to a
     * protocol mismatch or a newer, unsupported event—the system wraps it in a
     * {@link RawStreamDataChunk} and labels it with this type. This allows the rest of the
     * pipeline to log the anomaly or gracefully degrade without crashing.
     * </p>
     */
    UNKNOWN(RawStreamDataChunk.class),

    /**
     * Identifies the role (e.g., {@code "assistant"}) that will be associated with the
     * following content chunks.
     * <p>
     * In conversational models, the role is typically emitted once per turn to signal that
     * the subsequent text and tool calls originate from the assistant. Representing it as a
     * {@link TextStreamDataChunk} simplifies uniform processing—the role is just another
     * piece of textual metadata that can be stored or forwarded unchanged.
     * </p>
     */
    ROLE(TextStreamDataChunk.class),

    /**
     * Contains the model’s internal chain‑of‑thought or reasoning steps before formulating
     * the final answer.
     * <p>
     * Some models are designed to expose their intermediate reasoning (also known as
     * “thinking” tokens) to improve transparency and trust. These fragments are delivered
     * ahead of the actual answer and can be displayed separately in a UI (e.g., in a
     * collapsible panel) or filtered out entirely. The content is textual, hence the re‑use
     * of {@link TextStreamDataChunk}.
     * </p>
     */
    REASONING_CONTENT(TextStreamDataChunk.class),

    /**
     * Represents the core textual output generated by the model as its response to the user.
     * <p>
     * This is the primary content that the end‑user sees. It may arrive in multiple
     * successive chunks as the model generates tokens, and consuming code typically
     * concatenates these fragments to reconstruct the complete answer.
     * </p>
     */
    ANSWER_CONTENT(TextStreamDataChunk.class),

    /**
     * Signifies a request from the model to invoke an external tool or function.
     * <p>
     * When a model decides that a user’s request requires external computation or data
     * retrieval, it emits a tool‑call event containing the function name and arguments.
     * The {@link ToolCallStreamDataChunk} carries this information in a structured form that
     * can be easily deserialized and dispatched to the appropriate tool.
     * </p>
     */
    TOOL_CALL(ToolCallStreamDataChunk.class),

    /**
     * Carries token‑usage statistics, typically presented at the end of a streaming response.
     * <p>
     * Usage data includes the number of prompt and completion tokens consumed, which is
     * essential for cost monitoring, rate limiting, and logging. Because its structure
     * differs from textual content, it is encapsulated in a dedicated
     * {@link UsageStreamDataChunk}.
     * </p>
     */
    USAGE(UsageStreamDataChunk.class),

    /**
     * Marks the successful completion of the streaming response.
     * <p>
     * After all other chunks have been emitted, the stream sends a terminal signal (often a
     * sentinel like {@code "[DONE]"}). Mapping this to {@link TextStreamDataChunk} allows
     * the processing pipeline to close resources, notify listeners, or perform cleanup
     * without introducing a separate chunk type for a purely signaling event.
     * </p>
     */
    FINISHED(TextStreamDataChunk.class),

    ;

    /**
     * The {@link StreamDataChunk} subclass that contains the actual payload for this
     * stream data type.
     * <p>
     * This binding enables type‑safe dispatch: given a {@code StreamDataType}, consumers
     * can infer the expected concrete chunk class and safely downcast or pattern‑match
     * without resorting to {@code instanceof} checks scattered throughout the codebase.
     * </p>
     */
    private final Class<? extends StreamDataChunk> dataChunkType;
}