/*
 *    Copyright 2025-2026 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package pro.chenggang.project.reactive.ai.lite.core.option;

/**
 * Defines the types of data that can be expected in a streaming response from an AI service.
 * This enum helps in identifying and processing different parts of the incoming data stream.
 *
 * @author Cheng Gang
 * @version 0.1.0
 */
public enum StreamDataType {

    /**
     * Represents the original message content sent in the request.
     */
    REQUEST_MESSAGE,

    /**
     * Represents the reasoning or thought process of the AI model, which may be streamed before the final answer.
     */
    REASONING_CONTENT,

    /**
     * Represents the main answer or content generated by the AI model.
     */
    ANSWER_CONTENT,

    /**
     * Represents a request from the model to call a tool or function.
     */
    TOOL_CALL,

    /**
     * Represents metadata about the model's usage, such as token counts, often sent at the end of a stream.
     */
    USAGE,

    ;

}
