/*
 *    Copyright 2025-2026 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package pro.chenggang.project.reactive.ai.lite.core.certification.defaults;

import lombok.AccessLevel;
import lombok.Builder;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import org.springframework.web.util.UriBuilder;
import pro.chenggang.project.reactive.ai.lite.core.certification.TokenCertification;

/**
 * An implementation of {@link TokenCertification} that applies authentication tokens
 * as URI query parameters directly to a {@link UriBuilder}. This approach is used when
 * external AI or API services expect credentials (e.g., API keys) to be embedded in the
 * request URL rather than in HTTP headers.
 * <p>
 * Instances are created via the provided {@link Builder} pattern (generated by Lombok)
 * and are immutable once built. Each certification is associated with a profile
 * (e.g., a named account or configuration set) and can optionally act as the default
 * for that profile.
 * <p>
 * Typical usage involves obtaining a configured instance, then calling
 * {@link #applyTo(UriBuilder)} to enrich a URI before execution.
 *
 * @author Gang Cheng
 * @version 0.1.0
 * @see TokenCertification
 */
@Builder
@RequiredArgsConstructor(access = AccessLevel.PRIVATE)
public class UriTokenCertification implements TokenCertification {

    /**
     * The profile identifier that groups related certifications together.
     * Profiles allow multiple certification configurations to coexist
     * and be selected at runtime based on the active environment or account.
     */
    @NonNull
    private final String profile;

    /**
     * The name of the URI query parameter under which the token value will be
     * transmitted. Common examples include {@code "key"} or {@code "api_key"}.
     * This value is used as the key when appending the parameter to the URI.
     */
    @NonNull
    private final String name;

    /**
     * The actual authentication token value, such as an API key or bearer secret,
     * that grants access to the target service. It is appended as the value
     * corresponding to the {@link #name} query parameter.
     */
    @NonNull
    private final String token;

    /**
     * A flag indicating whether this certification should be considered the
     * default for its associated {@link #profile}. When multiple certifications
     * are available for a profile, the default may be applied automatically
     * if no explicit choice is made.
     */
    private final boolean isDefault;

    /**
     * Returns the profile name associated with this certification.
     * The profile serves as a logical grouping key for authentication
     * strategies and is used when resolving which certification to apply.
     *
     * @return the profile string
     */
    @Override
    public String profile() {
        return this.profile;
    }

    /**
     * Indicates whether this certification acts as the default for its profile.
     * Default certifications may be applied automatically by the framework
     * when no specific certification is designated, simplifying configuration
     * for common scenarios.
     *
     * @return {@code true} if this is the default certification, {@code false} otherwise
     */
    @Override
    public boolean isDefault() {
        return isDefault;
    }

    /**
     * Returns the name of the query parameter used to transmit the token.
     * The token value sent to the service corresponds to this key in the
     * URI's query string.
     *
     * @return the query parameter name (e.g., {@code "api_key"})
     */
    @Override
    public String name() {
        return this.name;
    }

    /**
     * Returns the authentication token value that will be attached to requests.
     * This value should be treated as sensitive and securely stored.
     *
     * @return the token string, never {@code null}
     */
    @Override
    public String token() {
        return this.token;
    }

    /**
     * Appends the token as a query parameter to the given {@link UriBuilder}.
     * This method mutates the builder by adding a new query parameter using
     * {@link #name()} as the key and {@link #token()} as the value.
     * <p>
     * It is typically called during URI construction for AI service callbacks
     * where the API expects authentication information in the URL string.
     * The underlying {@link UriBuilder} handles proper encoding of the
     * parameter values.
     *
     * @param uriBuilder the Spring {@link UriBuilder} to which the token
     *                   query parameter will be added; must not be {@code null}
     */
    public void applyTo(@NonNull UriBuilder uriBuilder) {
        uriBuilder.queryParam(name, token);
    }
}