/*
 *    Copyright 2025-2026 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package pro.chenggang.project.reactive.ai.lite.core.entity.usage;

import com.fasterxml.jackson.databind.node.ObjectNode;
import lombok.AccessLevel;
import lombok.Builder;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import lombok.extern.jackson.Jacksonized;
import org.springframework.lang.Nullable;

/**
 * The default, immutable implementation of the {@link Usage} interface.
 * <p>
 * This class serves as the canonical representation of token usage metrics returned by a
 * language model API. It is designed to be constructed via its Lombok-generated builder
 * and can be seamlessly serialized/deserialized with Jackson thanks to the {@code @Jacksonized}
 * annotation. Each token count field is initialized to {@code 0} by default to maintain
 * a safe, predictable state even if the underlying API omits certain metrics.
 * </p>
 * <p>
 * Because the class is immutable, all state must be supplied at construction time. The
 * builder allows partial specification (e.g., only prompt and completion tokens) while
 * defaulting the remaining fields to zero. The {@code rawUsage} field is nullable and
 * stores any additional, model-specific usage data that does not map to the standard
 * token fields. This provides extensibility while preserving the standard contract.
 * </p>
 *
 * @author Gang Cheng
 * @version 0.1.0
 * @see Usage
 */
@Jacksonized
@Builder
@RequiredArgsConstructor(access = AccessLevel.PRIVATE)
public class DefaultUsage implements Usage {

    /**
     * The number of tokens consumed by the input prompt.
     * <p>
     * In natural language processing, prompt tokens are the tokens that represent the
     * input text or context provided to the model. This field captures that metric as
     * reported by the API. A default value of {@code 0} is used to handle cases where
     * the API does not include this information (e.g., in streaming scenarios where usage
     * is reported at the end).
     * </p>
     */
    @NonNull
    @Builder.Default
    private final Integer promptTokens = 0;

    /**
     * The number of tokens generated by the model in the completion.
     * <p>
     * Completion tokens correspond to the output text produced by the language model in
     * response to the prompt. This count is often used to calculate billing or
     * estimate output length. Like other token fields, it defaults to {@code 0} to
     * gracefully handle missing data.
     * </p>
     */
    @NonNull
    @Builder.Default
    private final Integer completionTokens = 0;

    /**
     * The number of tokens used for other purposes beyond the main prompt and completion.
     * <p>
     * Some models differentiate additional token usage, for example those consumed by
     * function calling, system messages, or special formatting tokens. This field
     * captures such auxiliary usage. Its default is {@code 0}, reflecting the common
     * case where no extra tokens are used.
     * </p>
     */
    @NonNull
    @Builder.Default
    private final Integer otherTokens = 0;

    /**
     * The total number of tokens consumed for the entire request.
     * <p>
     * This is often the sum of {@link #promptTokens}, {@link #completionTokens}, and
     * {@link #otherTokens}, but may also include additional internal tokens depending
     * on the API implementation. It provides a single convenient metric for billing or
     * usage monitoring. The default value is {@code 0} to handle incomplete API
     * responses.
     * </p>
     */
    @NonNull
    @Builder.Default
    private final Integer totalTokens = 0;

    /**
     * The raw, unparsed usage data as returned by the underlying API.
     * <p>
     * This field holds a Jackson {@link ObjectNode} that preserves the original JSON
     * structure of the usage response. It is valuable for logging, debugging, or when
     * the API returns metrics that do not map to the standard token fields. The field
     * is nullable because not all APIs provide raw data, or it may be intentionally
     * omitted during construction.
     * </p>
     */
    @Nullable
    private final ObjectNode rawUsage;

    /**
     * Returns the number of prompt tokens.
     * <p>
     * This method provides the count of tokens that were processed as input to the
     * model. It is part of the {@link Usage} interface contract and can be used for
     * cost estimation, rate limiting, or user feedback.
     * </p>
     * @return prompt token count, never {@code null}, defaulting to {@code 0}
     */
    @Override
    public Integer getPromptTokens() {
        return this.promptTokens;
    }

    /**
     * Returns the number of completion tokens.
     * <p>
     * This method supplies the count of tokens that were generated by the model in
     * its response. It is useful for monitoring output length limits and calculating
     * billing. A return value of {@code 0} indicates either no output was generated
     * or the metric was not provided.
     * </p>
     * @return completion token count, never {@code null}, defaulting to {@code 0}
     */
    @Override
    public Integer getCompletionTokens() {
        return this.completionTokens;
    }

    /**
     * Returns the number of other (auxiliary) tokens.
     * <p>
     * This method exposes the count of tokens that are neither prompt nor completion
     * tokens, such as those used for function calling or special formatting. It is
     * included in the interface for completeness and may be used to obtain a fully
     * detailed breakdown of token consumption.
     * </p>
     * @return other token count, never {@code null}, defaulting to {@code 0}
     */
    @Override
    public Integer getOtherTokens() {
        return this.otherTokens;
    }

    /**
     * Returns the total number of tokens used.
     * <p>
     * This method provides an aggregated view of all token consumption for the request.
     * While it may equal the sum of prompt, completion, and other tokens, it can also
     * include additional internal counts dictated by the model provider. It is the
     * primary metric for overall usage tracking.
     * </p>
     * @return total token count, never {@code null}, defaulting to {@code 0}
     */
    @Override
    public Integer getTotalTokens() {
        return this.totalTokens;
    }

    /**
     * Returns the raw usage data as an {@link ObjectNode}, or {@code null} if not set.
     * <p>
     * Access to the raw JSON tree allows clients to retrieve any extra usage
     * information that is not captured by the standard token fields. This is
     * particularly helpful when dealing with custom model outputs or when detailed
     * debugging is required. The return value is nullable to indicate the absence of
     * raw data.
     * </p>
     * @return the raw usage node, or {@code null} if unavailable
     */
    @Nullable
    @Override
    public ObjectNode getRawUsage() {
        return this.rawUsage;
    }

}