/*
 *    Copyright 2025-2026 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package pro.chenggang.project.reactive.ai.lite.core.message.chunk;

import lombok.AccessLevel;
import lombok.Builder;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.extern.jackson.Jacksonized;
import pro.chenggang.project.reactive.ai.lite.core.entity.AttributesAbility;
import pro.chenggang.project.reactive.ai.lite.core.entity.values.AbstractAttribute;
import pro.chenggang.project.reactive.ai.lite.core.option.StreamDataType;

/**
 * A concrete implementation of {@link StreamDataChunk} that carries string-based data.
 * <p>
 * In reactive streaming, chunks of data are emitted sequentially, and each chunk may
 * belong to different categories (e.g., answer text, reasoning traces, source references).
 * This class distinguishes between these categories via {@link #dataType}, enabling downstream
 * processors to interpret and route the raw text appropriately. The text itself is stored
 * in {@link #value} as an immutable string fragment.
 * </p>
 * <p>
 * By extending {@link AbstractAttribute}, this class gains the ability to hold additional
 * metadata through the {@link AttributesAbility} interface, which can be used to attach
 * auxiliary information such as confidence scores or invocation IDs.
 * </p>
 *
 * @author Gang Cheng
 * @version 0.1.0
 * @see StreamDataChunk
 * @see StreamDataType
 * @see AttributesAbility
 */
@Jacksonized
@Builder
@RequiredArgsConstructor(access = AccessLevel.PRIVATE)
public class TextStreamDataChunk extends AbstractAttribute implements StreamDataChunk, AttributesAbility {

    /**
     * The stream data type that categorizes this chunk's content.
     * <p>
     * Different downstream components may need to treat content differently based on its type.
     * For instance, an answer content chunk may be appended to a final message, while a
     * reasoning content chunk may be displayed in a separate debug panel. Storing the type
     * alongside the value allows generic handling code to make type-aware decisions without
     * parsing the text.
     * </p>
     */
    private final StreamDataType dataType;

    /**
     * The string payload of this stream chunk, representing one fragment of the total stream.
     * <p>
     * This value is typically a partial sentence, a token, or a complete phrase that together
     * with other chunks forms the full output. It is immutable and accessible via the
     * {@code getValue()} getter generated by Lombok.
     * </p>
     */
    @Getter
    private final String value;

    /**
     * Retrieves the {@link StreamDataType} that describes the purpose of this chunk's textual content.
     * <p>
     * This method is part of the {@link StreamDataChunk} contract and provides a runtime
     * mechanism for consumers to determine how this chunk should be processed. For example,
     * a filtering processor might ignore all chunks that are not of type {@code ANSWER_CONTENT}.
     * </p>
     *
     * @return the non-null {@link StreamDataType} representing the chunk's content category
     */
    @Override
    public StreamDataType getDataType() {
        return this.dataType;
    }
}