/*
 *    Copyright 2025-2026 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package pro.chenggang.project.reactive.ai.lite.client.openai.dto;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AccessLevel;
import lombok.Builder;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Value;
import lombok.extern.jackson.Jacksonized;
import pro.chenggang.project.reactive.ai.lite.core.option.Role;

import java.util.List;

/**
 * Represents a single message within an OpenAI chat completion conversation.
 * It encapsulates the role of the author (e.g., system, user, assistant), the 
 * textual or media content, tool calls, and associated metadata.
 *
 * @author Gang Cheng
 * @version 0.1.0
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Builder
@Jacksonized
@RequiredArgsConstructor(access = AccessLevel.PRIVATE)
public class ChatCompletionMessage {

    /**
     * The role of the messages author (e.g., {@code system}, {@code user}, {@code assistant}, {@code tool}).
     */
    @JsonProperty("role")
    private final Role role;

    /**
     * An optional name for the participant. Provides the model information to differentiate 
     * between participants of the same role.
     */
    @JsonProperty("name")
    private final String name;

    /**
     * The contents of the message. This can be a String for simple text messages,
     * or a List of {@link MediaContent} objects for multimodal inputs.
     */
    @JsonProperty("content")
    private final Object rawContent;

    /**
     * Tool call that this message is responding to (used specifically for {@code tool} role messages).
     */
    @JsonProperty("tool_call_id")
    private final String toolCallId;

    /**
     * The tool calls generated by the model, such as function calls.
     */
    @JsonProperty("tool_calls")
    @JsonFormat(with = JsonFormat.Feature.ACCEPT_SINGLE_VALUE_AS_ARRAY)
    private final List<ToolCall> toolCalls;

    /**
     * The reasoning content generated by reasoning models (e.g., o1 models) before the final response.
     */
    @JsonProperty("reasoning_content")
    private final String reasoningContent;


    /**
     * Represents a specific tool invocation requested by the model during a chat completion.
     */
    @JsonInclude(Include.NON_NULL)
    @JsonIgnoreProperties(ignoreUnknown = true)
    @Getter
    @Builder
    @Jacksonized
    @RequiredArgsConstructor(access = AccessLevel.PRIVATE)
    public static class ToolCall {

        /**
         * The index of the tool call in the sequence.
         */
        @JsonProperty("index")
        private final Integer index;

        /**
         * The unique identifier for the tool call.
         */
        @JsonProperty("id")
        private final String id;

        /**
         * The type of the tool. Typically "function".
         */
        @JsonProperty("type")
        private final String type;

        /**
         * The function that the model called.
         */
        @JsonProperty("function")
        private final ChatCompletionFunction function;

    }

    /**
     * Represents the specific function name and arguments requested by the model.
     */
    @JsonInclude(Include.NON_NULL)
    @JsonIgnoreProperties(ignoreUnknown = true)
    @Getter
    @Builder
    @Jacksonized
    @RequiredArgsConstructor(access = AccessLevel.PRIVATE)
    public static class ChatCompletionFunction {

        /**
         * The name of the function to call.
         */
        @JsonProperty("name")
        private final String name;

        /**
         * The arguments to call the function with, as generated by the model in JSON format.
         */
        @JsonProperty("arguments")
        private final String arguments;
    }


    /**
     * Represents complex multimodal content parts for a message, such as text combined with images, audio, or files.
     */
    @JsonInclude(Include.NON_NULL)
    @JsonIgnoreProperties(ignoreUnknown = true)
    @Getter
    @RequiredArgsConstructor(access = AccessLevel.PRIVATE)
    public static class MediaContent {

        /**
         * The type of the content part (e.g., "text", "image_url", "input_audio", "file").
         */
        @JsonProperty("type")
        private final String type;

        /**
         * The text content, if the type is "text".
         */
        @JsonProperty("text")
        private final String text;

        /**
         * The image URL content, if the type is "image_url".
         */
        @JsonProperty("image_url")
        private final ImageUrl imageUrl;

        /**
         * The audio content, if the type is "input_audio".
         */
        @JsonProperty("input_audio")
        private final InputAudio inputAudio;

        /**
         * The file content, if the type is "file".
         */
        @JsonProperty("file")
        private final InputFile inputFile;

        /**
         * Creates a text media content part.
         *
         * @param text The text payload.
         * @return A new {@link MediaContent} instance of type text.
         */
        public static MediaContent of(String text) {
            return new MediaContent("text", text, null, null, null);
        }

        /**
         * Creates an image media content part.
         *
         * @param imageUrl The image URL object.
         * @return A new {@link MediaContent} instance of type image_url.
         */
        public static MediaContent of(ImageUrl imageUrl) {
            return new MediaContent("image_url", null, imageUrl, null, null);
        }

        /**
         * Creates an audio media content part.
         *
         * @param inputAudio The input audio object.
         * @return A new {@link MediaContent} instance of type input_audio.
         */
        public static MediaContent of(InputAudio inputAudio) {
            return new MediaContent("input_audio", null, null, inputAudio, null);
        }

        /**
         * Creates a file media content part.
         *
         * @param inputFile The input file object.
         * @return A new {@link MediaContent} instance of type file.
         */
        public static MediaContent of(InputFile inputFile) {
            return new MediaContent("file", null, null, null, inputFile);
        }
    }

    /**
     * Represents audio input provided to the model.
     */
    @JsonInclude(Include.NON_NULL)
    @Value(staticConstructor = "of")
    public static class InputAudio {

        /**
         * The base64 encoded audio data.
         */
        @JsonProperty("data")
        String data;

        /**
         * The format of the encoded audio (e.g., MP3 or WAV).
         */
        @JsonProperty("format")
        Format format;

        /**
         * Supported audio formats.
         */
        public enum Format {
            /**
             * MP3 audio format.
             */
            @JsonProperty("mp3") MP3,
            /**
             * WAV audio format.
             */
            @JsonProperty("wav") WAV
        }
    }

    /**
     * Represents an image URL provided to the model, which can be an external HTTP link or base64 data URI.
     */
    @JsonInclude(Include.NON_NULL)
    @Value(staticConstructor = "of")
    public static class ImageUrl {

        /**
         * The URL or base64 data URI of the image.
         */
        @JsonProperty("url")
        String url;

        /**
         * Specifies the detail level of the image analysis (e.g., "low", "high", "auto").
         */
        @JsonProperty("detail")
        String detail;

    }

    /**
     * Represents a file input provided to the model.
     */
    @Value(staticConstructor = "of")
    public static class InputFile {
        /**
         * The name of the file.
         */
        @JsonProperty("filename")
        String filename;

        /**
         * The content or data of the file.
         */
        @JsonProperty("file_data")
        String fileData;
    }

}