/*
 *    Copyright 2025-2026 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package pro.chenggang.project.reactive.ai.lite.client.openai.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AccessLevel;
import lombok.Builder;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.extern.jackson.Jacksonized;

import java.util.Map;

/**
 * Represents the response format configuration for OpenAI API requests.
 * <p>
 * This class is used to specify how the OpenAI model should format its output.
 * It supports standard text output, ensuring the output is a valid JSON object,
 * or enforcing a strict JSON schema that the output must adhere to.
 * </p>
 *
 * @author Gang Cheng
 * @version 0.1.0
 */
@JsonInclude(Include.NON_NULL)
@Getter
@Builder
@Jacksonized
@RequiredArgsConstructor(access = AccessLevel.PRIVATE)
public class ResponseFormat {

    /**
     * The type of response format to be generated by the model.
     * <p>
     * Must be one of {@code text}, {@code json_object}, or {@code json_schema}.
     * </p>
     */
    @JsonProperty("type")
    private final Type type;

    /**
     * The JSON schema object that describes the required format of the JSON output.
     * <p>
     * This field is only applicable and required when the {@link #type} is set
     * to {@link Type#JSON_SCHEMA}.
     * </p>
     */
    @JsonProperty("json_schema")
    private final JsonSchema jsonSchema;

    /**
     * Defines the available types of response formats supported by the OpenAI API.
     */
    public enum Type {

        /**
         * Instructs the model to generate a standard text response.
         * This is the default behavior if no format is specified.
         */
        @JsonProperty("text")
        TEXT,

        /**
         * Enables JSON mode, which guarantees that the message generated by the
         * model is a valid JSON object.
         */
        @JsonProperty("json_object")
        JSON_OBJECT,

        /**
         * Enables Structured Outputs, which guarantees that the model's output
         * will strictly match the supplied JSON schema.
         */
        @JsonProperty("json_schema")
        JSON_SCHEMA

    }

    /**
     * Represents the JSON schema definition for Structured Outputs.
     * <p>
     * This class is utilized to define the exact structure of the JSON response
     * expected from the model when the response format type is {@code json_schema}.
     * </p>
     */
    @JsonInclude(Include.NON_NULL)
    @Getter
    @Builder
    @Jacksonized
    @RequiredArgsConstructor(access = AccessLevel.PRIVATE)
    public static class JsonSchema {

        /**
         * The name of the JSON schema.
         * <p>
         * This provides a recognizable identifier for the schema being supplied.
         * </p>
         */
        @JsonProperty("name")
        private final String name;

        /**
         * The actual JSON schema definition.
         * <p>
         * This map contains the schema rules (e.g., properties, types, required fields)
         * that the model's output must follow.
         * </p>
         */
        @JsonProperty("schema")
        private final Map<String, Object> schema;

        /**
         * Indicates whether strict schema adherence should be enforced.
         * <p>
         * When set to {@code true}, the model is guaranteed to follow the schema
         * exactly, with no additional properties allowed unless specified.
         * </p>
         */
        @JsonProperty("strict")
        private final Boolean strict;

    }

}
