/*
 *    Copyright 2025-2026 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package pro.chenggang.project.reactive.ai.lite.core.message;

import org.springframework.lang.Nullable;
import pro.chenggang.project.reactive.ai.lite.core.entity.AttributesAbility;
import pro.chenggang.project.reactive.ai.lite.core.option.Role;

/**
 * Represents a text-based message generated by the AI assistant (LLM model).
 * <p>
 * This interface defines the structure for responses returned by the model. It extends
 * the base {@link Message} interface and inherently assigns the {@link Role#ASSISTANT} role.
 * It can contain the final text answer as well as optional reasoning content (e.g.,
 * model's internal "thoughts").
 * </p>
 *
 * @author Cheng Gang
 * @version 0.1.0
 */
public interface AssistantTextMessage extends Message, AttributesAbility {

    /**
     * Returns the role identifier for assistant messages.
     * <p>
     * This method provides the default role value for messages generated by AI assistants.
     * It overrides the {@link Message#getRole()} method to return the specific role constant
     * for assistant-type messages, which is always "assistant".
     * </p>
     *
     * @return the string value of the ASSISTANT role
     */
    @Override
    default String getRole() {
        return Role.ASSISTANT.getValue();
    }

    /**
     * Returns the primary textual content of the message generated by the assistant.
     * <p>
     * This represents the final answer provided to the user. It may be null if the
     * assistant only returned tool calls without text content.
     * </p>
     *
     * @return the text content of the message, or {@code null}
     */
    @Nullable
    String getContent();

    /**
     * Returns the reasoning content associated with the message, if any.
     * <p>
     * Reasoning content often represents the model's internal thought process or
     * chain-of-thought before generating the final text content. This is a feature
     * supported by some specific models (e.g., DeepSeek Reasoner).
     * </p>
     *
     * @return the reasoning content, or {@code null} if not available
     */
    @Nullable
    String getReasoningContent();

}
