/*
 *    Copyright 2025-2026 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package pro.chenggang.project.reactive.ai.lite.core.message;

import org.springframework.lang.Nullable;
import pro.chenggang.project.reactive.ai.lite.core.option.Role;

/**
 * A {@link MediaMessage} that originates from an AI assistant and may include generated
 * multimedia content such as images or audio.
 * <p>
 * This interface is a specialization that enforces the {@link Role#ASSISTANT} role,
 * ensuring that any media content is interpreted as coming from the AI. It overrides
 * the {@code getRole()} method to return the constant string "assistant" and also
 * refines the nullability contracts of {@code getContent()} and {@code getReasoningContent()}
 * to better reflect the optional nature of textual components in assistant responses.
 * </p>
 * <p>
 * In typical usage, implementations of this interface are created by the framework when
 * an AI model returns a response containing both text and media (e.g., a generated image
 * with a description). The assistant may also provide reasoning content in scenarios
 * supporting chain-of-thought or explainability features.
 * </p>
 *
 * @author Gang Cheng
 * @version 0.1.0
 */
public interface AssistantMediaMessage extends MediaMessage {

    /**
     * Provides the role identifier for this message type, which is always "assistant".
     * <p>
     * Overriding this method guarantees that any processing logic expecting a
     * media message from the assistant does not need to check the role dynamically.
     * It returns exactly the value of {@link Role#ASSISTANT#getValue()}, making the
     * code more predictable and less error-prone when serializing or routing messages.
     * </p>
     *
     * @return the string constant "assistant"
     */
    @Override
    default String getRole() {
        return Role.ASSISTANT.getValue();
    }

    /**
     * Returns the textual content generated by the assistant together with the media,
     * or {@code null} if the assistant produced only multimedia without any descriptive text.
     * <p>
     * This override explicitly states that the content may be missing. In media-centric
     * responses, the assistant might focus on generating an image or audio and not
     * include an accompanying text—identical to how a real assistant might silently
     * create a graphic. Callers must handle the {@code null} case when a text explanation
     * is required.
     * </p>
     *
     * @return the text component of the message, possibly {@code null}
     */
    @Nullable
    @Override
    String getContent();

    /**
     * Returns the reasoning content provided by the assistant for explainability,
     * or {@code null} if no reasoning was generated.
     * <p>
     * Reasoning content is often an intermediate thought process, generated by models
     * that support "chain-of-thought" or step‑by‑step reasoning features. Since not
     * all models or modes of interaction produce such content, this method declares
     * it as nullable to reflect its optional nature.
     * </p>
     *
     * @return the reasoning text if available, otherwise {@code null}
     */
    @Nullable
    @Override
    String getReasoningContent();

}