/*
 *    Copyright 2025-2026 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package pro.chenggang.project.reactive.ai.lite.core.message;

import org.springframework.lang.Nullable;
import pro.chenggang.project.reactive.ai.lite.core.option.Role;

/**
 * Represents an assistant message that includes media content, such as generated images or audio.
 * <p>
 * This interface extends {@link MediaMessage} to indicate that the content (both text
 * and media) was generated by an AI model in the role of an assistant. It inherits
 * the standard parsingAttributes of media messages while enforcing the {@link Role#ASSISTANT} role.
 * </p>
 *
 * @author Gang Cheng
 * @version 0.1.0
 */
public interface AssistantMediaMessage extends MediaMessage {

    /**
     * Returns the role identifier for assistant messages.
     * <p>
     * This method overrides the {@link Message#getRole()} method to provide the
     * specific role constant for assistant-type messages, which is always "assistant".
     * </p>
     *
     * @return the string value of the ASSISTANT role
     */
    @Override
    default String getRole() {
        return Role.ASSISTANT.getValue();
    }

    /**
     * Returns the primary textual content generated by the assistant alongside the media.
     *
     * @return the text content of the message, or {@code null} if only media was generated
     */
    @Nullable
    @Override
    String getContent();

    /**
     * Returns the reasoning content associated with the message, if any.
     *
     * @return the reasoning content, or {@code null} if not available
     */
    @Nullable
    @Override
    String getReasoningContent();

}
