/*
 *    Copyright 2025-2026 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package pro.chenggang.project.reactive.ai.lite.core.message;

import org.springframework.lang.Nullable;
import pro.chenggang.project.reactive.ai.lite.core.entity.AttributesAbility;
import pro.chenggang.project.reactive.ai.lite.core.option.Role;

/**
 * A message that represents a text response generated by an AI assistant.
 *
 * <p>This interface models the output of a language model after processing a user request.
 * It is a specialized {@link Message} that always prescribes the {@link Role#ASSISTANT} role
 * and additionally extends {@link AttributesAbility} to allow attachment of arbitrary metadata.
 * Implementations typically hold the final text answer, an optional reasoning trace, and
 * possible tool call details (see sub-interfaces).</p>
 *
 * <p>In an AI conversation flow, an instance of this type is returned from the model following
 * a user prompt. Its {@link #getContent()} provides the direct response, while
 * {@link #getReasoningContent()} can expose internal thought processes when supported
 * (e.g., by models like DeepSeek Reasoner).</p>
 *
 * @author Gang Cheng
 * @version 0.1.0
 * @see Message
 * @see AttributesAbility
 * @see Role
 */
public interface AssistantTextMessage extends Message, AttributesAbility {

    /**
     * Returns the role of this message, which is always "assistant".
     *
     * <p>This implementation overrides the parent {@link Message#getRole()} to provide
     * a fixed role value. Every assistant message carries this fixed role to distinguish
     * it from other participants in a conversation (e.g., user, system).</p>
     *
     * @return the string representation of the {@link Role#ASSISTANT} constant
     */
    @Override
    default String getRole() {
        return Role.ASSISTANT.getValue();
    }

    /**
     * Returns the primary textual content of the assistant's reply.
     *
     * <p>This content is the final answer intended for the user. It may be {@code null}
     * when the assistant responds exclusively with tool calls or other non-textual
     * actions. In such cases, the message may be refined into a more specific subtype
     * (e.g., {@code AssistantToolMessage}) that carries those details.</p>
     *
     * @return the assistant's text message, or {@code null} if no textual content is present
     */
    @Nullable
    String getContent();

    /**
     * Returns the reasoning content associated with this message, if available.
     *
     * <p>Some advanced language models expose an internal chain-of-thought before
     * producing the final answer. This reasoning is typically hidden from end-users
     * but can be useful for debugging, evaluation, or explainability. It is model-
     * specific and may be {@code null} when the underlying provider does not support
     * reasoning output (e.g., standard completion models).</p>
     *
     * @return the reasoning trace, or {@code null} if not available
     * @see <a href="https://deepseek.com">DeepSeek Reasoner</a>
     */
    @Nullable
    String getReasoningContent();

}