/*
 *    Copyright 2025-2026 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package pro.chenggang.project.reactive.ai.lite.core.message;

import lombok.NonNull;
import pro.chenggang.project.reactive.ai.lite.core.message.defaults.DefaultToolResultMessage;
import pro.chenggang.project.reactive.ai.lite.core.message.defaults.DefaultToolResultMessage.DefaultToolResultMessageBuilder;
import pro.chenggang.project.reactive.ai.lite.core.option.Role;

/**
 * A message carrying the output from a locally executed tool back to the AI model.
 * <p>
 * In tool‑augmented conversations, an AI model may request the execution of a
 * function through a {@link ToolCallMessage}. The application then runs the
 * requested tool and must return its result to the model so that the model can
 * formulate the final answer for the user. This interface defines the shape of
 * that result message. Each {@code ToolResultMessage} is inherently immutable
 * after construction and is designed to be used in a reactive pipeline.
 * </p>
 * <p>
 * The message must contain the original tool‑call identifier (the
 * {@code toolCallId}) exactly as emitted by the model. This correlation is
 * crucial for the model to match the output with the prior request, especially
 * when multiple tool calls are in flight. The result content – typically a
 * JSON string – is the raw return value of the tool.
 * </p>
 *
 * @author Gang Cheng
 * @version 0.1.0
 */
public interface ToolResultMessage extends Message {

    /**
     * Returns the role identifier for this message type.
     * <p>
     * All tool‑result messages are assigned the fixed role {@link Role#TOOL}.
     * This allows the AI model to distinguish tool outputs from user messages
     * or its own assistant messages, and to process the tool result appropriately
     * within the conversation thread. The role is not configurable because it
     * is an inherent property of the message's purpose.
     * </p>
     *
     * @return the string value of the TOOL role, always {@code "tool"}
     */
    @Override
    default String getRole() {
        return Role.TOOL.getValue();
    }

    /**
     * Obtains the unique identifier of the tool call whose execution produced this result.
     * <p>
     * This identifier must exactly match the {@code id} field of a
     * {@link ToolCallMessage.AssistantToolCall} that the AI model previously
     * emitted. During multi‑step interactions, the model relies on this
     * matching to understand which result belongs to which request. Failure
     * to provide the correct identifier will cause the model to ignore the
     * result or generate an error.
     * </p>
     *
     * @return the tool call identifier, never {@code null}
     */
    String toolCallId();

    /**
     * Returns the actual output data generated by the tool execution.
     * <p>
     * This content is the direct result of invoking the tool, often serialized
     * into a JSON representation. The model will consume this content to
     * incorporate into its final response to the user. Therefore, the string
     * should faithfully represent the tool’s return value and may include
     * structured data, textual summaries, or error details.
     * </p>
     *
     * @return the result content as a string; may be empty but not {@code null}
     */
    String content();

    /**
     * Creates a new builder for constructing a {@link ToolResultMessage} with the required tool call ID.
     * <p>
     * This factory method initiates the builder pattern, ensuring that the
     * tool result message always carries the mandatory correlation identifier.
     * After calling this method, the caller must set the {@code content} via
     * the builder’s {@code content(String)} method before building the final
     * immutable message instance. The builder is provided by the default
     * implementation, {@link DefaultToolResultMessage}.
     * </p>
     *
     * @param toolCallId the unique identifier of the tool call that produced this result;
     *                   must not be {@code null}
     * @return a new {@link DefaultToolResultMessageBuilder} instance, never {@code null}
     */
    static DefaultToolResultMessageBuilder newToolResultMessage(@NonNull String toolCallId) {
        return DefaultToolResultMessage.builder()
                .toolCallId(toolCallId);
    }
}