/*
 *    Copyright 2025-2026 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package pro.chenggang.project.reactive.ai.lite.core.message;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import lombok.AccessLevel;
import lombok.Builder;
import lombok.Getter;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import lombok.extern.jackson.Jacksonized;
import org.springframework.lang.Nullable;
import org.springframework.util.StringUtils;
import pro.chenggang.project.reactive.ai.lite.core.exception.LlmClientException;
import pro.chenggang.project.reactive.ai.lite.core.tool.ToolDefinition;

import java.util.List;

import static pro.chenggang.project.reactive.ai.lite.core.util.JsonRelatedUtil.OBJECT_MAPPER;

/**
 * Represents a message generated by the assistant (LLM) that requests the invocation of one or more tools (functions).
 * <p>
 * In an AI interaction cycle, when the model deems that it cannot fulfill the user's request with its built-in
 * knowledge alone, it responds with a {@code ToolCallMessage} instead of a plain text answer. This message encapsulates
 * one or more tool calls that the host application must execute locally. After executing the tool(s), the application
 * should send back a {@link ToolResultMessage} containing the outcomes, enabling the model to incorporate real-time data
 * into its subsequent reasoning.
 * </p>
 * <p>
 * This interface extends {@link AssistantTextMessage}, meaning it can optionally carry a textual summary alongside
 * the tool call instructions, though the primary payload is the list of {@link AssistantToolCall} objects.
 * </p>
 *
 * @author Gang Cheng
 * @version 0.1.0
 * @see AssistantToolCall
 * @see ToolResultMessage
 * @see ToolDefinition
 */
public interface ToolCallMessage extends AssistantTextMessage {

    /**
     * Retrieves the list of tool calls that the assistant model wants to execute.
     * <p>
     * The order of the list reflects the sequence in which the LLM intended the tools to be invoked,
     * which may be important for dependent calculations. Each tool call comes with a unique identifier
     * and the function’s name together with its serialized arguments.
     * </p>
     *
     * @return a non‑null, possibly empty list of {@link AssistantToolCall} objects
     */
    List<AssistantToolCall> getToolCalls();

    /**
     * Encapsulates a single tool invocation request issued by the AI model.
     * <p>
     * Each {@code AssistantToolCall} contains all the information required to execute a tool locally:
     * a unique correlation ID (generated by the model), the function’s name and its JSON arguments,
     * and a reference to the original {@link ToolDefinition} that was provided to the LLM. The
     * definition aids in validation and routing within the host application.
     * </p>
     * <p>
     * Instances are typically created through the Lombok-generated builder, which populates the
     * private constructor via the {@code @RequiredArgsConstructor} annotation.
     * </p>
     *
     * @author Gang Cheng
     */
    @Getter
    @Jacksonized
    @Builder
    @RequiredArgsConstructor(access = AccessLevel.PRIVATE)
    class AssistantToolCall {

        /**
         * The ordinal position of this tool call within the current message’s sequence.
         * <p>
         * This index preserves the order reported by the LLM, which may be relevant when
         * multiple tool calls depend on each other. The host application can process the
         * calls sequentially based on this field.
         * </p>
         */
        @NonNull
        private final Integer index;

        /**
         * The unique identifier assigned by the LLM to this specific tool call.
         * <p>
         * This ID must be echoed in the {@link ToolResultMessage} so that the AI model can
         * correlate the tool’s output with the original request. Without a correct match,
         * the model might ignore the result or misattribute it.
         * </p>
         */
        @NonNull
        private final String id;

        /**
         * The type of the tool call, nearly always {@code "function"}.
         * <p>
         * This field mirrors the standard response structure defined by many AI providers.
         * It is used internally for validation and can be extended if other call types are
         * ever supported.
         * </p>
         */
        @NonNull
        private final String type;

        /**
         * The function details, including the name and the JSON‑encoded arguments
         * that the model wishes to pass.
         */
        @NonNull
        private final AssistantToolCallFunction function;

        /**
         * The original tool definition that was registered with the AI system.
         * <p>
         * It carries the complete schema, description, and execution metadata,
         * enabling the application to validate the request and invoke the correct
         * implementation.
         * </p>
         */
        @NonNull
        private final ToolDefinition toolDefinition;

    }

    /**
     * Represents the core of a tool call: the function’s name and its serialized arguments.
     * <p>
     * This class serves as a container for the two essential pieces of a function invocation
     * request. The arguments are stored as a raw JSON string to faithfully preserve the
     * model’s output. The string may be empty or {@code null}, in which case the private
     * constructor defaults to {@code "{}"} to avoid parsing errors downstream.
     * </p>
     *
     * @author Gang Cheng
     */
    @Getter
    class AssistantToolCallFunction {

        /**
         * The name of the function to execute.
         * <p>
         * This must exactly match the name specified in the corresponding
         * {@link ToolDefinition}. The application will use this name for dispatch.
         * </p>
         */
        @NonNull
        private final String name;

        /**
         * A JSON string containing the parameters for the function.
         * <p>
         * The string follows the JSON‑schema defined in the tool’s definition. When the
         * LLM provides no arguments, this field defaults to {@code "{}"} via the constructor
         * logic to guarantee a valid JSON object at all times.
         * </p>
         */
        @NonNull
        private final String arguments;

        /**
         * Private constructor used by the Lombok builder and Jackson deserialization.
         * <p>
         * If the supplied {@code arguments} are {@code null} or blank, the field is
         * automatically set to {@code "{}"}, ensuring that every caller can safely parse
         * the JSON without an explicit null check.
         * </p>
         *
         * @param name      the exact function name (must not be {@code null})
         * @param arguments the JSON arguments string; may be {@code null} or empty,
         *                  in which case {@code "{}"} is used
         */
        @Jacksonized
        @Builder
        private AssistantToolCallFunction(@NonNull String name, @Nullable String arguments) {
            this.name = name;
            if (StringUtils.hasText(arguments)) {
                this.arguments = arguments;
            } else {
                this.arguments = "{}";
            }
        }

        /**
         * Parses the stored JSON argument string into a Jackson {@link JsonNode} tree.
         * <p>
         * This method is the recommended way to extract typed parameter values:
         * <pre>{@code
         * JsonNode args = toolCallFunction.jsonArguments();
         * String city = args.get("city").asText();
         * double temperature = args.get("temperature").asDouble();
         * }</pre>
         * </p>
         * <p>
         * If the LLM produced malformed JSON (a severe error in the model’s output),
         * an {@link LlmClientException} is thrown to alert the host application.
         * </p>
         *
         * @return a non‑null {@link JsonNode} representing the parsed arguments
         * @throws LlmClientException if the arguments string is not valid JSON
         */
        public JsonNode jsonArguments() {
            try {
                return OBJECT_MAPPER.readTree(this.arguments);
            } catch (JsonProcessingException e) {
                throw new LlmClientException("Failed to parse tool call arguments: " + this.arguments, e);
            }
        }
    }

}