/*
 *    Copyright 2025-2026 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package pro.chenggang.project.reactive.ai.lite.core.message;

import pro.chenggang.project.reactive.ai.lite.core.option.Role;

/**
 * Represents the response or output generated by executing a tool locally.
 * <p>
 * When an AI model requests a tool call (via a {@link ToolCallMessage}), the system
 * executes the tool and then sends the results back to the model as a ToolResultMessage.
 * This message must contain the original tool call ID to allow the model to correlate
 * the output with its request.
 * </p>
 *
 * @author Cheng Gang
 * @version 0.1.0
 */
public interface ToolResultMessage extends Message {

    /**
     * Returns the role of this message.
     * <p>
     * For tool result messages, the role is inherently and always {@link Role#TOOL}.
     * </p>
     *
     * @return the string value of the TOOL role
     */
    @Override
    default String getRole() {
        return Role.TOOL.getValue();
    }

    /**
     * Returns the unique identifier of the tool call that produced this result.
     * <p>
     * This ID must exactly match the ID provided by the model in the preceding
     * {@link ToolCallMessage.AssistantToolCall} to correctly associate the output.
     * </p>
     *
     * @return the tool call identifier
     */
    String toolCallId();

    /**
     * Returns the actual output or result data produced by the tool execution.
     * <p>
     * This content is typically a JSON string representing the return value of
     * the local function. The model will parse this content to formulate its
     * final answer to the user.
     * </p>
     *
     * @return the result content of the tool execution
     */
    String content();
}
