/*
 *    Copyright 2025-2026 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package pro.chenggang.project.reactive.ai.lite.core.message;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import lombok.AccessLevel;
import lombok.Builder;
import lombok.Getter;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import lombok.extern.jackson.Jacksonized;
import org.springframework.lang.Nullable;
import org.springframework.util.StringUtils;
import pro.chenggang.project.reactive.ai.lite.core.exception.LlmClientException;
import pro.chenggang.project.reactive.ai.lite.core.tool.ToolDefinition;

import java.util.List;

import static pro.chenggang.project.reactive.ai.lite.core.util.JsonRelatedUtil.OBJECT_MAPPER;

/**
 * Represents a message generated by the assistant (LLM) that requests the invocation of one or more tools.
 * <p>
 * When an AI model decides that it needs to use a provided tool (function) to answer a user's request,
 * it returns a ToolCallMessage instead of (or in addition to) a standard text response. This message
 * contains the necessary information to execute the tool locally.
 * </p>
 *
 * @author Gang Cheng
 * @version 0.1.0
 */
public interface ToolCallMessage extends AssistantTextMessage {

    /**
     * Gets the list of tool calls requested by the assistant in this message.
     *
     * @return a list of {@link AssistantToolCall} objects representing the requested tool invocations
     */
    List<AssistantToolCall> getToolCalls();

    /**
     * Represents a single tool call request made by the assistant.
     * <p>
     * This class encapsulates all the information required to execute a specific tool,
     * including a unique ID for correlation, the function name and arguments, and a
     * reference to the original {@link ToolDefinition}.
     * </p>
     *
     * @author Gang Cheng
     */
    @Getter
    @Jacksonized
    @Builder
    @RequiredArgsConstructor(access = AccessLevel.PRIVATE)
    class AssistantToolCall {

        /**
         * The index of this tool call within the sequence of tool calls in the current message.
         * Useful for maintaining order when processing multiple simultaneous tool calls.
         */
        @NonNull
        private final Integer index;

        /**
         * The unique identifier generated by the LLM for this specific tool call.
         * This ID must be included in the corresponding {@link ToolResultMessage} to correlate the response.
         */
        @NonNull
        private final String id;

        /**
         * The type of the tool call (e.g., "function").
         */
        @NonNull
        private final String type;

        /**
         * The specific function details, including its name and the arguments generated by the model.
         */
        @NonNull
        private final AssistantToolCallFunction function;

        /**
         * The original tool definition that this call corresponds to.
         */
        @NonNull
        private final ToolDefinition toolDefinition;

    }

    /**
     * Represents the specific function invocation details within an {@link AssistantToolCall}.
     * <p>
     * It contains the name of the function to execute and the arguments provided by the
     * AI model in JSON format.
     * </p>
     *
     * @author Gang Cheng
     */
    @Getter
    class AssistantToolCallFunction {

        /**
         * The name of the function to execute.
         */
        @NonNull
        private final String name;

        /**
         * The JSON string containing the arguments to pass to the function.
         */
        @NonNull
        private final String arguments;

        /**
         * Constructs a new {@link AssistantToolCallFunction}.
         * <p>
         * If the provided arguments string is empty or null, it defaults to an empty JSON object "{}".
         * </p>
         *
         * @param name      the name of the function
         * @param arguments the JSON string of arguments
         */
        @Jacksonized
        @Builder
        private AssistantToolCallFunction(@NonNull String name, @Nullable String arguments) {
            this.name = name;
            if (StringUtils.hasText(arguments)) {
                this.arguments = arguments;
            } else {
                this.arguments = "{}";
            }
        }

        /**
         * Parses the JSON string arguments into a structured {@link JsonNode}.
         * <p>
         * This is a convenience method to make it easier to extract individual argument values.
         * </p>
         *
         * @return a {@link JsonNode} representing the parsed arguments
         * @throws RuntimeException if the arguments string is not valid JSON
         */
        public JsonNode jsonArguments() {
            try {
                return OBJECT_MAPPER.readTree(this.arguments);
            } catch (JsonProcessingException e) {
                throw new LlmClientException("Failed to parse tool call arguments: " + this.arguments, e);
            }
        }
    }

}
