/*
 *    Copyright 2025-2026 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package pro.chenggang.project.reactive.ai.lite.core.execution.response;

import lombok.Getter;
import lombok.experimental.SuperBuilder;

import java.util.List;

/**
 * Represents the response from an embedding‑type language model request.
 * <p>
 * This class extends {@link ExtractedLlmResponse} to include the resultant embedding vectors.
 * Each element in the {@code embeddings} list corresponds to an input string, holding its numerical
 * vector representation as a {@code float[]}. The ordering of the outer list matches the order of
 * the input texts supplied in the embedding request.
 * <p>
 * Instances are typically created via the super builder pattern, which is generated by the
 * {@link SuperBuilder} annotation and inherits builder capabilities from the parent class.
 *
 * @author Gang Cheng
 * @version 0.1.0
 */
@Getter
@SuperBuilder
public class EmbeddingResponse extends ExtractedLlmResponse {

    /**
     * The list of embedding vectors produced by the language model.
     * <p>
     * Each inner {@code float[]} array represents the dense vector embedding for a single input text.
     * The outer list maintains the same order as the inputs provided to the embedding request. This
     * field is exclusively used in embedding scenarios and is {@code final} to ensure immutability
     * of the response data.
     */
    protected final List<float[]> embeddings;

}