/*
 *    Copyright 2025-2026 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package pro.chenggang.project.reactive.ai.lite.core.execution.response;

import lombok.Getter;
import lombok.experimental.SuperBuilder;
import pro.chenggang.project.reactive.ai.lite.core.message.AssistantTextMessage;
import pro.chenggang.project.reactive.ai.lite.core.message.ToolCallMessage;
import pro.chenggang.project.reactive.ai.lite.core.message.ToolCallMessage.AssistantToolCall;

import java.util.List;
import java.util.Optional;

/**
 * Represents the final, high-level response for a non-streaming chat completion request.
 * <p>
 * This class abstracts the provider-specific raw JSON into a unified object that carries
 * the generated assistant message (text or tool calls), any embeddings (for embedding
 * models), and critical metadata such as token usage, model information, and finish
 * reason, which are inherited from {@link ExtractedLlmResponse}.
 * </p>
 * <p>
 * The assistant message can be plain text ({@link AssistantTextMessage}) or a request
 * to invoke tools ({@link ToolCallMessage}). Clients can use {@link #getToolCalls()}
 * to safely access tool calls without type checks.
 * </p>
 * <p>
 * Because this class extends {@link ExtractedLlmResponse}, it also provides token usage
 * details and other metadata that are essential for monitoring, billing, and logging.
 * </p>
 *
 * @author Gang Cheng
 * @version 0.1.0
 * @see ExtractedLlmResponse
 * @see AssistantTextMessage
 * @see ToolCallMessage
 */
@Getter
@SuperBuilder
public class GeneralResponse extends ExtractedLlmResponse {

    /**
     * The parsed assistant message generated by the model.
     * <p>
     * Depending on the model's decision, this field can be either a plain
     * {@link AssistantTextMessage} (carrying the textual answer) or a
     * {@link ToolCallMessage} (containing a list of tool invocation requests).
     * Use {@code instanceof} checks or the convenience method {@link #getToolCalls()}
     * to determine which subtype is present.
     * </p>
     */
    protected final AssistantTextMessage assistantTextMessage;

    /**
     * Safely retrieves the list of tool calls from the assistant message, if the
     * assistant message is a {@link ToolCallMessage}.
     * <p>
     * This method encapsulates the type check and avoids the need for callers to
     * manually inspect the {@link #assistantTextMessage} type. It returns an empty
     * {@link Optional} when the assistant message is a plain text message or when
     * the tool call list itself is absent within a {@link ToolCallMessage}.
     * </p>
     *
     * @return an {@link Optional} containing the list of {@link AssistantToolCall} items,
     * or {@link Optional#empty()} if the assistant message does not contain any tool calls.
     */
    public Optional<List<AssistantToolCall>> getToolCalls() {
        if (!(assistantTextMessage instanceof ToolCallMessage toolCallMessage)) {
            return Optional.empty();
        }
        return Optional.ofNullable(toolCallMessage.getToolCalls());
    }
}