/*
 *    Copyright 2025-2026 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package pro.chenggang.project.reactive.ai.lite.core.execution.response;

import lombok.AccessLevel;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.experimental.SuperBuilder;
import pro.chenggang.project.reactive.ai.lite.core.entity.context.ExecutionContext;

/**
 * Abstract base class for all Large Language Model (LLM) response types.
 * <p>
 * This class forms the root of the response hierarchy within the reactive-ai-lite framework,
 * ensuring that every concrete response (e.g., plain text, streaming, structured) is
 * intrinsically linked to the {@link ExecutionContext} that produced it. The execution
 * context carries the original request parameters, conversation history, and any
 * intermediate state, enabling full traceability and correlation between a request and
 * its resulting response. This is critical for debugging, logging, auditing, and
 * implementing features like continuation or response verification.
 * </p>
 * <p>
 * The class uses Lombok annotations to reduce boilerplate:
 * <ul>
 *   <li>{@link SuperBuilder @SuperBuilder} generates a builder that can be extended
 *       by subclasses, enabling fluent construction of response hierarchies.</li>
 *   <li>{@link RequiredArgsConstructor} with {@code PROTECTED} access creates a
 *       constructor that accepts the {@code executionContext} field, which
 *       subclasses can delegate to.</li>
 *   <li>{@link Getter @Getter} exposes the execution context for inspection without
 *       direct mutation (the field is {@code final}).</li>
 * </ul>
 * Because the class is abstract, it cannot be instantiated directly; only concrete
 * subclasses (e.g., {@link GeneralResponse}, {@link StreamResponse}) are intended
 * for use.
 * </p>
 *
 * @author Gang Cheng
 * @version 0.1.0
 */
@Getter
@SuperBuilder
@RequiredArgsConstructor(access = AccessLevel.PROTECTED)
public abstract class LlmResponse {

    /**
     * The execution context that was active when this response was generated.
     * It holds all input parameters, prompt templates, conversation state,
     * and metadata necessary to reconstruct the exact conditions under which the LLM
     * produced this response. This field is immutable ({@code final}) and is set at
     * construction time, typically via the builder generated by {@link SuperBuilder}.
     * Its presence allows downstream components to tie the response back to the
     * original request, supporting features such as logging, retry, or
     * result aggregation.
     */
    protected final ExecutionContext executionContext;

}