/*
 *    Copyright 2025-2026 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package pro.chenggang.project.reactive.ai.lite.core.execution.response;

import lombok.Getter;
import lombok.experimental.SuperBuilder;
import pro.chenggang.project.reactive.ai.lite.core.message.chunk.StreamDataChunk;

/**
 * A concrete {@link LlmResponse} for carrying a single, parsed chunk of streaming output.
 * <p>
 * During reactive streaming of LLM completions, raw server-sent events (SSE) are parsed
 * and mapped to discrete {@link StreamDataChunk} objects. Each chunk may represent different
 * event types such as text fragments, tool call requests, or usage statistics. This class
 * wraps exactly one such chunk, providing a clean abstraction that hides the underlying SSE
 * protocol details from downstream consumers.
 * </p>
 * <p>
 * By separating the chunk data from the common metadata inherited from {@link LlmResponse},
 * this design enables the framework to uniformly handle both streaming and non-streaming
 * responses through a shared type hierarchy. The {@link SuperBuilder} annotation allows
 * easy construction using a builder pattern that respects the parent class properties,
 * ensuring consistent initialization across layers.
 * </p>
 * <p>
 * Instances are intended to be immutable value objects, typically generated by the reactive
 * pipeline and consumed by result accumulation or event handlers.
 * </p>
 *
 * @author Gang Cheng
 * @version 0.1.0
 * @see StreamDataChunk
 */
@Getter
@SuperBuilder
public class StreamResponse extends LlmResponse {

    /**
     * The parsed chunk of streaming data extracted from an SSE event.
     * <p>
     * This field holds the actual content and type information for this particular
     * segment of the streaming response. The {@link StreamDataChunk} encapsulates
     * metadata such as the chunk index and the content type (e.g., text delta,
     * tool call instructions, or end-of-stream markers), enabling type-safe
     * processing of heterogeneous stream fragments.
     * </p>
     * <p>
     * Because it is declared {@code final} and annotated with {@link Getter},
     * the chunk can be safely shared and accessed without risk of modification
     * throughout the reactive pipeline.
     * </p>
     *
     * @see StreamDataChunk
     */
    private final StreamDataChunk dataChunk;

}