/*
 *    Copyright 2025-2026 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package pro.chenggang.project.reactive.ai.lite.client.deepseek.dto;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AccessLevel;
import lombok.Builder;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.extern.jackson.Jacksonized;
import pro.chenggang.project.reactive.ai.lite.core.option.Role;

import java.util.List;

/**
 * Represents a single message within a DeepSeek chat completion response.
 * Corresponds to the message structure returned by the DeepSeek API, which can
 * include text content, tool calls, and optional reasoning content. This DTO is
 * designed for immutable, Jackson-serializable construction via the {@link Builder}
 * pattern. The {@code rawContent} field is typed as {@link Object} to accept both
 * plain string content and structured multimodal content (e.g., arrays of content parts).
 *
 * @author Gang Cheng
 * @version 0.1.0
 * @see <a href="https://platform.deepseek.com/api-docs/">DeepSeek API Documentation</a>
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Builder
@Jacksonized
@RequiredArgsConstructor(access = AccessLevel.PRIVATE)
public class ChatCompletionMessage {

    /**
     * The role of the message author. One of {@code system}, {@code user}, {@code assistant},
     * or {@code tool}, as defined by the {@link Role} enum.
     */
    @JsonProperty("role")
    private final Role role;

    /**
     * An optional name for the participant. Typically used to differentiate between
     * different users or assistant instances in a multi-party conversation.
     */
    @JsonProperty("name")
    private final String name;

    /**
     * The content of the message. Can be a plain text string or, for multimodal responses,
     * a list of content parts (e.g., text + image). The raw type allows flexible
     * deserialization based on the API response.
     */
    @JsonProperty("content")
    private final Object rawContent;

    /**
     * The tool call ID this message is responding to, required when the role is {@code tool}.
     * Links the message back to an earlier assistant message that requested a tool invocation.
     */
    @JsonProperty("tool_call_id")
    private final String toolCallId;

    /**
     * The list of tool calls generated by the model in an assistant message.
     * Each {@link ToolCall} describes a function the model wants to invoke, including
     * function name and arguments. The field accepts a single value as an array for
     * simpler API consumption.
     */
    @JsonProperty("tool_calls")
    @JsonFormat(with = JsonFormat.Feature.ACCEPT_SINGLE_VALUE_AS_ARRAY)
    private final List<ToolCall> toolCalls;

    /**
     * Optional reasoning content provided by some models (e.g., DeepSeek‑R1) before the
     * final answer. This content may contain chain‑of‑thought information and is not part
     * of the usual conversation history, but can be useful for debugging or explanation.
     */
    @JsonProperty("reasoning_content")
    private final String reasoningContent;

    /**
     * Represents a single tool call generated by an assistant message. Contains the
     * index within the tool_calls array, a unique tool call ID, the type of tool
     * (currently always {@code "function"}), and the function details to be invoked.
     */
    @JsonInclude(Include.NON_NULL)
    @JsonIgnoreProperties(ignoreUnknown = true)
    @Getter
    @Builder
    @Jacksonized
    @RequiredArgsConstructor(access = AccessLevel.PRIVATE)
    public static class ToolCall {

        /**
         * The index of this tool call in the {@code tool_calls} array. Useful for
         * ordering when multiple tool calls are generated in one message.
         */
        @JsonProperty("index")
        private final Integer index;

        /**
         * The unique identifier for this tool call. Used by the client to match a
         * subsequent tool response message back to this request.
         */
        @JsonProperty("id")
        private final String id;

        /**
         * The type of the tool. Currently only {@code "function"} is supported.
         */
        @JsonProperty("type")
        private final String type;

        /**
         * The function that should be called, including its name and arguments.
         */
        @JsonProperty("function")
        private final ChatCompletionFunction function;

    }

    /**
     * Describes a function to be called by a tool call. Contains the function name
     * and a JSON‑encoded argument string that the client is expected to parse and
     * use when invoking the external function.
     */
    @JsonInclude(Include.NON_NULL)
    @JsonIgnoreProperties(ignoreUnknown = true)
    @Getter
    @Builder
    @Jacksonized
    @RequiredArgsConstructor(access = AccessLevel.PRIVATE)
    public static class ChatCompletionFunction {

        /**
         * The name of the function to call, as defined in the model's tool configuration.
         */
        @JsonProperty("name")
        private final String name;

        /**
         * The arguments to pass to the function as a JSON string. The client is responsible
         * for parsing this string into an appropriate object.
         */
        @JsonProperty("arguments")
        private final String arguments;
    }

}