/*
 *    Copyright 2025-2026 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package pro.chenggang.project.reactive.ai.lite.core.message.defaults;

import lombok.AccessLevel;
import lombok.Builder;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import lombok.Singular;
import lombok.extern.jackson.Jacksonized;
import org.springframework.lang.Nullable;
import pro.chenggang.project.reactive.ai.lite.core.entity.values.AbstractAttribute;
import pro.chenggang.project.reactive.ai.lite.core.message.Message;
import pro.chenggang.project.reactive.ai.lite.core.message.ToolCallMessage;

import java.util.List;

/**
 * The default, immutable implementation of the {@link ToolCallMessage} interface.
 * <p>
 * This class represents a message generated by the AI assistant that requests the
 * invocation of one or more tools. It uses Lombok's {@code @Builder} with {@code @Singular}
 * for convenient list construction, and is annotated with {@code @Jacksonized} to
 * support JSON serialization and deserialization.
 * </p>
 *
 * @author Cheng Gang
 * @version 0.1.0
 */
@Jacksonized
@Builder
@RequiredArgsConstructor(access = AccessLevel.PRIVATE)
public class DefaultToolCallMessage extends AbstractAttribute implements ToolCallMessage {

    /**
     * The primary textual content of the message, if any.
     */
    @Nullable
    private final String content;

    /**
     * The reasoning content associated with the message, if any.
     */
    @Nullable
    private final String reasoningContent;

    /**
     * The list of tool calls requested by the assistant.
     */
    @NonNull
    @Singular
    private final List<AssistantToolCall> toolCalls;

    /**
     * Retrieves the list of requested tool calls.
     *
     * @return a list of {@link AssistantToolCall} objects
     */
    @Override
    public List<AssistantToolCall> getToolCalls() {
        return this.toolCalls;
    }

    /**
     * Retrieves the primary textual content of the message.
     *
     * @return the text content, or {@code null} if only tool calls are present
     */
    @Override
    public String getContent() {
        return this.content;
    }

    /**
     * Retrieves the reasoning content associated with the message.
     *
     * @return the reasoning content, or {@code null} if not available
     */
    @Nullable
    @Override
    public String getReasoningContent() {
        return this.reasoningContent;
    }

    /**
     * Retrieves the actual concrete type of this message.
     *
     * @return the {@link DefaultToolCallMessage} class type
     */
    @Override
    public Class<? extends Message> getActualType() {
        return DefaultToolCallMessage.class;
    }
}
