/*
 *    Copyright 2025-2026 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package pro.chenggang.project.reactive.ai.lite.core.message.defaults;

import lombok.AccessLevel;
import lombok.Builder;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import lombok.extern.jackson.Jacksonized;
import pro.chenggang.project.reactive.ai.lite.core.message.Message;
import pro.chenggang.project.reactive.ai.lite.core.message.ToolResultMessage;

/**
 * Default, immutable implementation of the {@link ToolResultMessage} interface, representing
 * the outcome of a tool invocation within a reactive AI interaction.
 *
 * <p>
 * This class serves as a value object that captures both the identifier of the originating
 * tool call and the textual content produced by the tool. It is designed to be constructed
 * via its {@link Builder} (generated by Lombok) and is fully {@link Jacksonized} for seamless
 * JSON serialization/deserialization in web and messaging contexts.
 * </p>
 *
 * <p>
 * Instances of this class are used downstream to correlate tool results with their requests,
 * enabling stateful conversation flows where the AI model waits for tool outputs before
 * generating the next response.
 * </p>
 *
 * @author Gang Cheng
 * @version 0.1.0
 * @see ToolResultMessage
 */
@Jacksonized
@Builder
@RequiredArgsConstructor(access = AccessLevel.PRIVATE)
public class DefaultToolResultMessage implements ToolResultMessage {

    /**
     * The unique identifier of the tool call that produced this result.
     * <p>
     * This ID links the result back to the original tool invocation request, allowing
     * the system to maintain conversation context and correctly sequence responses.
     * </p>
     */
    @NonNull
    private final String toolCallId;

    /**
     * The textual output or data returned by the tool execution.
     * <p>
     * The format and meaning of this content depend on the specific tool; it may be
     * plain text, structured data (e.g., JSON), or any other representation agreed
     * upon by the tool implementation and the consuming AI model.
     * </p>
     */
    @NonNull
    private final String content;

    /**
     * Returns the unique identifier of the tool call that originated this result.
     *
     * <p>
     * This value is essential for matching tool results to their corresponding
     * {@link pro.chenggang.project.reactive.ai.lite.core.message.ToolExecutionRequestMessage}
     * in a multi-turn conversation.
     * </p>
     *
     * @return the tool call identifier
     */
    @Override
    public String toolCallId() {
        return this.toolCallId;
    }

    /**
     * Returns the content produced by the tool after execution.
     *
     * <p>
     * The returned string represents the tool’s output as-is; it may be further parsed
     * or processed by the AI model depending on the downstream logic.
     * </p>
     *
     * @return the tool result content
     */
    @Override
    public String content() {
        return this.content;
    }

    /**
     * Provides the concrete runtime type of this message.
     *
     * <p>
     * This method enables type-based discrimination in polymorphic processing,
     * especially useful for routing, logging, or serialization frameworks that need
     * to distinguish between different {@link Message} implementations without relying
     * on {@code instanceof} checks.
     * </p>
     *
     * @return the {@link DefaultToolResultMessage} class type
     */
    @Override
    public Class<? extends Message> getActualType() {
        return DefaultToolResultMessage.class;
    }
}